//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameState
    {
        public GameState()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int ID { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
