//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLeaderboard
    {
        public GameLeaderboard()
        {
            this.PlayerGameResults = new HashSet<PlayerGameResult>();
            this.RoundLeaderboards = new HashSet<RoundLeaderboard>();
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public int NumberOfRounds { get; set; }
        public int NumberOfPlayers { get; set; }
        public int CurrentRoundNumber { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<PlayerGameResult> PlayerGameResults { get; set; }
        public virtual ICollection<RoundLeaderboard> RoundLeaderboards { get; set; }
    }
}
