//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.FoursomePlayers = new HashSet<FoursomePlayer>();
            this.PlayerGameResults = new HashSet<PlayerGameResult>();
            this.PlayerRoundResults = new HashSet<PlayerRoundResult>();
            this.RoundPlayerHandicaps = new HashSet<RoundPlayerHandicap>();
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PlayerIndex { get; set; }
    
        public virtual ICollection<FoursomePlayer> FoursomePlayers { get; set; }
        public virtual Game Game { get; set; }
        public virtual ICollection<PlayerGameResult> PlayerGameResults { get; set; }
        public virtual ICollection<PlayerRoundResult> PlayerRoundResults { get; set; }
        public virtual ICollection<RoundPlayerHandicap> RoundPlayerHandicaps { get; set; }
    }
}
