//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGameResult
    {
        public PlayerGameResult()
        {
            this.Scorecards = new HashSet<Scorecard>();
            this.PlayerRoundResults = new HashSet<PlayerRoundResult>();
        }
    
        public int ID { get; set; }
        public int GameLeaderboardID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> GameRank { get; set; }
        public Nullable<int> GameAdjustedPar { get; set; }
        public Nullable<int> GameAdjustedTotal { get; set; }
        public Nullable<int> GameNotAdjustedPar { get; set; }
        public Nullable<int> GameNotAdjustedTotal { get; set; }
    
        public virtual GameLeaderboard GameLeaderboard { get; set; }
        public virtual Player Player { get; set; }
        public virtual ICollection<Scorecard> Scorecards { get; set; }
        public virtual ICollection<PlayerRoundResult> PlayerRoundResults { get; set; }
    }
}
