//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundFoursome
    {
        public RoundFoursome()
        {
            this.FoursomePlayers = new HashSet<FoursomePlayer>();
            this.Scorecards = new HashSet<Scorecard>();
        }
    
        public int ID { get; set; }
        public int RoundID { get; set; }
        public string Name { get; set; }
        public int FoursomeNumberInRound { get; set; }
    
        public virtual ICollection<FoursomePlayer> FoursomePlayers { get; set; }
        public virtual Round Round { get; set; }
        public virtual ICollection<Scorecard> Scorecards { get; set; }
    }
}
