//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundLeaderboard
    {
        public RoundLeaderboard()
        {
            this.PlayerRoundResults = new HashSet<PlayerRoundResult>();
        }
    
        public int ID { get; set; }
        public int GameLeaderboardID { get; set; }
        public int RoundNumberInGame { get; set; }
        public int GameID { get; set; }
    
        public virtual GameLeaderboard GameLeaderboard { get; set; }
        public virtual Game Game { get; set; }
        public virtual ICollection<PlayerRoundResult> PlayerRoundResults { get; set; }
    }
}
