//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundPlayerHandicap
    {
        public int ID { get; set; }
        public int RoundID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> Handicap { get; set; }
        public string CalcHandicapFromIndex { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Round Round { get; set; }
    }
}
