//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundState
    {
        public RoundState()
        {
            this.Rounds = new HashSet<Round>();
        }
    
        public int ID { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Round> Rounds { get; set; }
    }
}
