//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public Round()
        {
            this.Holes = new HashSet<Hole>();
            this.RoundFoursomes = new HashSet<RoundFoursome>();
            this.RoundPlayerHandicaps = new HashSet<RoundPlayerHandicap>();
            this.RoundSetupStates = new HashSet<RoundSetupState>();
            this.Scorecards = new HashSet<Scorecard>();
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public int RoundNumberInGame { get; set; }
        public Nullable<int> HolesInRound { get; set; }
        public Nullable<int> Front9Total { get; set; }
        public Nullable<int> Back9Total { get; set; }
        public Nullable<int> FullRoundTotal { get; set; }
        public Nullable<int> Slope { get; set; }
        public int RoundStateID { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<Hole> Holes { get; set; }
        public virtual ICollection<RoundFoursome> RoundFoursomes { get; set; }
        public virtual ICollection<RoundPlayerHandicap> RoundPlayerHandicaps { get; set; }
        public virtual RoundState RoundState { get; set; }
        public virtual ICollection<RoundSetupState> RoundSetupStates { get; set; }
        public virtual ICollection<Scorecard> Scorecards { get; set; }
    }
}
