//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScorecardHole
    {
        public int ID { get; set; }
        public int ScorecardID { get; set; }
        public int HoleNumber { get; set; }
        public int Par { get; set; }
        public int Handicap { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> AdjustedScore { get; set; }
    
        public virtual Scorecard Scorecard { get; set; }
    }
}
