//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unscrambled.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scorecard
    {
        public Scorecard()
        {
            this.FoursomePlayers = new HashSet<FoursomePlayer>();
            this.ScorecardHoles = new HashSet<ScorecardHole>();
        }
    
        public int ID { get; set; }
        public int PlayerGameResultID { get; set; }
        public int PlayerRoundResultID { get; set; }
        public Nullable<int> Front9Total { get; set; }
        public Nullable<int> Back9Total { get; set; }
        public Nullable<int> FullRoundTotal { get; set; }
        public Nullable<int> Slope { get; set; }
        public Nullable<int> Strokes { get; set; }
        public int GameID { get; set; }
        public int RoundID { get; set; }
        public int FoursomeID { get; set; }
        public string PlayerName { get; set; }
    
        public virtual ICollection<FoursomePlayer> FoursomePlayers { get; set; }
        public virtual Game Game { get; set; }
        public virtual PlayerGameResult PlayerGameResult { get; set; }
        public virtual PlayerRoundResult PlayerRoundResult { get; set; }
        public virtual RoundFoursome RoundFoursome { get; set; }
        public virtual Round Round { get; set; }
        public virtual ICollection<ScorecardHole> ScorecardHoles { get; set; }
    }
}
